#!/usr/bin/env php
<?php

include __DIR__.'/vendor/autoload.php';

define('ROOT_PATH', __DIR__);
define('APP_PATH', ROOT_PATH.'/app');
define('CONFIG_PATH', ROOT_PATH.'/config');

$dotenv = Dotenv\Dotenv::createImmutable(ROOT_PATH);
$dotenv->load();

$app = new \App\ConsoleApp();
$app->handle($argv);