#!/usr/bin/env php
<?php

require_once('vendor/autoload.php');

define('ROOT_PATH', __DIR__);
define('APP_PATH', ROOT_PATH.'/app');
define('CONFIG_PATH', ROOT_PATH.'/config');
define('BOOTSTRAP_PATH', ROOT_PATH.'/bootstrap');

$dotenv = Dotenv\Dotenv::createImmutable(ROOT_PATH, '.env');
$dotenv->load();

$app = new \Carrot\Console\Application();
$app->run();